sudo: false
language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - python setup.py develop
  - pip install -e ."[test]"

script: 
  - pytest --cov=hapic tests

after_success:
  - coveralls
